name: movie_search
description: "Filmes search app using the TMDB API."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  dio: ^5.11.0
  either_dart: ^1.0.0
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.2
  flutter_svg: ^2.3.0
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/